function[e]=BVPf(a,b,alpha,beta,n)
A=zeros(n-1,n-1);
R=zeros(n-1,1);
h=(b-a)/n;
x=a:h:b;
for i=2:n-2
    A(i,i)=(2/h/h)+q(x(i))-(p(x(i))/h);
    A(i,i-1)=-((1/h/h));    
    A(i,i+1)=-((1/h/h)-(p(x(i))/h));
    R(i,1)=r(x(i));
end
A(1,2)=-((1/h/h)-(p(x(1))/h));
A(n-1,n-2)=-(1/h/h);  
A(1,1)=(2/h/h)+q(x(1))-(p(x(1))/h);
A(n-1,n-1)=(2/h/h)+q(x(n-1))-(p(x(n-1))/h);
R(1,1)=r(x(1))+((1/h/h)*alpha); 
R(n-1,1)=r(x(n-1))+(((1/h/h)-(p(x(n-1))/h))*beta); 
A;
R;
Y=A\R;
figure(ceil(rand(1)*9999999));
U(1)=alpha;
U(n+1)=beta;
U(2:n)=Y(1:n-1);
%plot(x,U,'r');
Y=(x-2)+(x.*exp(1-x))+(2.*(1-x).*exp(-x));
%Y=alpha:(beta-alpha)/n:beta;
er=abs((Y-U)./U);
e=max(er);
plot(x,U,'r',x,Y,'b');
figure(ceil(rand(1)*9999999));
plot(x,er);